#ifndef ESPSDKX_HALSTATUS_H
#define ESPSDKX_HALSTATUS_H

typedef enum {
  HAL_STATUS_BUSY = 10,

  HAL_STATUS_OK = 0,

  HAL_STATUS_UNSUPPORTED = -10,
  HAL_STATUS_UNIMPLEMENTED = -11
} hal_status_t;

#endif
