name: HardwareAgnostic
on: [push]

jobs:
  StaticAnalysis:
    runs-on: native
    steps: 
      - name: Clone the repository
        uses: https://data.forgejo.org/actions/checkout@v6

      - name: Run static analysis on driver code
        run: cppcheck --max-ctu-depth=10 ${{ forgejo.workspace }}/drivers
