name: STM32F1
on: [push]

env:
  FAMILY: stm32f1
  BOARD: bluepillplus
  CC: arm-none-eabi-gcc
  OBJCOPY: arm-none-eabi-objcopy

jobs:
  Build:
    runs-on: native
    steps:
      - name: Clone the repository
        uses: https://data.forgejo.org/actions/checkout@v6
        with:
          submodules: recursive

      - name: Build all modules
        working-directory: ${{ forgejo.workspace }}/tests/build
        run: make all

  StaticAnalysis:
    runs-on: native
    steps: 
      - name: Clone the repository
        uses: https://data.forgejo.org/actions/checkout@v6
        with:
          submodules: recursive

      - name: Run cppcheck on HAL sources
        run: cppcheck --max-ctu-depth=10 ${{ forgejo.workspace }}/hal

      - name: Run clang-tidy on HAL sources
        working-directory: ${{ forgejo.workspace }}/tests/build
        run: |
          make compile_commands.json
          find ${{ forgejo.workspace }}/hal -type f -name "*.c" -print0 | xargs -0 clang-tidy -p .
