src-$(CONFIG_GPIO)    += $(RTOS_DIR)/gpio.c
src-$(CONFIG_UART)    += $(RTOS_DIR)/uart.c
src-$(CONFIG_SPI)     += $(RTOS_DIR)/spi.c
src-$(CONFIG_USB)     += $(RTOS_DIR)/usb.c
src-$(CONFIG_TIMING)  += $(RTOS_DIR)/time.c
src-$(CONFIG_PINCTRL) += $(RTOS_DIR)/pinctrl.c
