#ifndef EPSDKX_HAL_STATUS_H
#define EPSDKX_HAL_STATUS_H

typedef enum {
  HAL_STATUS_BUSY = 2,
  HAL_STATUS_PENDING = 1,

  HAL_STATUS_OK = 0,

  HAL_STATUS_UNSUPPORTED = -1,
  HAL_STATUS_UNIMPLEMENTED = -2,

  HAL_STATUS_ERR_INVALID_ARG = -10,
  HAL_STATUS_ERR_TIMEOUT     = -11,
  HAL_STATUS_ERR_FAULT       = -12,
  HAL_STATUS_ERR_OVERFLOW    = -13,
} hal_status_e;

#endif
