src-$(CONFIG_GPIO)    += $(DRIVER_DIR)/gpio.c
src-$(CONFIG_UART)    += $(DRIVER_DIR)/uart.c
src-$(CONFIG_SPI)     += $(DRIVER_DIR)/spi.c
src-$(CONFIG_USB)     += $(DRIVER_DIR)/usb.c
src-$(CONFIG_TIMING)  += $(DRIVER_DIR)/time.c
src-$(CONFIG_PINCTRL) += $(DRIVER_DIR)/pinctrl.c
